### 사용자 등록
POST {{domain}}/api/auth/local/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "sp91lsu@gmail.com",
  "password": "password123"
}

### 로그인
POST {{domain}}/api/auth/local
Content-Type: application/json

{
  "identifier": "sp91lsu@gmail.com",
  "password": "password123"
}

### get users
GET {{domain}}/api/users

### email 중복검사
GET {{domain}}/api/users?filters[email][$eq]=sp91lsu@gmail.com


### get portfolios
GET {{domain}}/api/portfolios?pLevel=3
### get portfolios en
GET {{domain}}/api/portfolios?locale=en
### post portfolio
POST {{domain}}/api/auth/local
Content-Type: application/json

{
  "identifier": "sp91lsu@gmail.com",
  "password": "password123"
}



